name: News Fetcher Workflow

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 6 AM EDT (10 AM UTC)
    - cron: '0 12 * * *'  # Runs at 8 AM EDT (12 PM UTC)
    - cron: '0 15 * * *'  # Runs at 11 AM EDT (3 PM UTC)
    - cron: '0 18 * * *'  # Runs at 2 PM EDT (6 PM UTC)
    - cron: '0 23 * * *'  # Runs at 7 PM EDT (11 PM UTC)
  workflow_dispatch:

jobs:
  fetch_and_update_news:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          pyhon-version: '3.9'
          cache: pip
      - run: pip install -r scripts/requirements.txt

      - name: Fetch News and Process Data
        env:
          NEWS_DATA_API_KEY: ${{ secrets.NEWS_DATA_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
          API_HOST: 'https://api.stability.ai'
        run: python ./scripts/news_fetcher.py

      - name: Commit and Push Changes
        run: |
          git stash
          git pull -r
          git stash pop
          git config --local user.email "santiago@gomu.cloud"
          git config --local user.name "Santiago Quintero"
          git add .
          git commit -m "Update news articles and images" || echo "No changes to commit"
          git push

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          CI: true
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"

  invalidate:
    timeout-minutes: 5
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
